In [29]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [30]:
dataset = pd.read_csv('Data2.csv')
x = dataset.iloc[:, : -1].values
y = dataset.iloc[:, -1].values

In [31]:
print(dataset)

   Country  Work   Age   Salary Purchased
0   France     5  44.0  72000.0        No
1    Spain     7  27.0  48000.0       Yes
2  Germany     4  30.0  54000.0        No
3    Spain     1  38.0  61000.0        No
4  Germany     8  40.0      NaN       Yes
5   France    10  35.0  58000.0       Yes
6    Spain     3   NaN  52000.0        No
7   France    12  48.0  79000.0       Yes
8  Germany     2  50.0  83000.0        No
9   France    15  37.0  67000.0       Yes


In [32]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [33]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [34]:
print(x)

[['France' 5.0 44.0 72000.0]
 ['Spain' 7.0 27.0 48000.0]
 ['Germany' 4.0 30.0 54000.0]
 ['Spain' 1.0 38.0 61000.0]
 ['Germany' 8.0 40.0 nan]
 ['France' 10.0 35.0 58000.0]
 ['Spain' 3.0 38.77777777777778 52000.0]
 ['France' 12.0 48.0 79000.0]
 ['Germany' 2.0 50.0 83000.0]
 ['France' 15.0 37.0 67000.0]]


In [35]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [36]:
print(x)

[[1.0 0.0 0.0 5.0 44.0 72000.0]
 [0.0 0.0 1.0 7.0 27.0 48000.0]
 [0.0 1.0 0.0 4.0 30.0 54000.0]
 [0.0 0.0 1.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 8.0 40.0 nan]
 [1.0 0.0 0.0 10.0 35.0 58000.0]
 [0.0 0.0 1.0 3.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 12.0 48.0 79000.0]
 [0.0 1.0 0.0 2.0 50.0 83000.0]
 [1.0 0.0 0.0 15.0 37.0 67000.0]]


In [37]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [38]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [39]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [40]:
print(x_train)

[[0.0 0.0 1.0 3.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 8.0 40.0 nan]
 [1.0 0.0 0.0 5.0 44.0 72000.0]
 [0.0 0.0 1.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 7.0 27.0 48000.0]
 [1.0 0.0 0.0 12.0 48.0 79000.0]
 [0.0 1.0 0.0 2.0 50.0 83000.0]
 [1.0 0.0 0.0 10.0 35.0 58000.0]]


In [41]:
print(x_test)

[[0.0 1.0 0.0 4.0 30.0 54000.0]
 [1.0 0.0 0.0 15.0 37.0 67000.0]]


In [42]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [43]:
print(x_train)

[[0.0 0.0 1.0 -0.816496580927726 -0.19159184384578545 -1.0182239953527132]
 [0.0 1.0 0.0 0.5443310539518174 -0.014117293757057777 nan]
 [1.0 0.0 0.0 -0.2721655269759087 0.566708506533324 0.583476671494251]
 [0.0 0.0 1.0 -1.3608276348795434 -0.30453019390224867
  -0.2974586952715793]
 [0.0 0.0 1.0 0.2721655269759087 -1.9018011447007988 -1.3385641287221062]
 [1.0 0.0 0.0 1.632993161855452 1.1475343068237058 1.1440719048906884]
 [0.0 1.0 0.0 -1.0886621079036347 1.4379472069688968 1.4644120382600814]
 [1.0 0.0 0.0 1.0886621079036347 -0.7401495441200351 -0.537713795298624]]
